$$
  M=
\left[ {\begin{array}{ccccc}
    1 & 2 & 3 & 4 & 5\\
   3 & 4 & 5 & 6 & 7\\
  \end{array} } \right]
$$

In [3]:
import numpy as np

Numpy is the matrix operation library of Python 

Let's first create a list of the numbers seen in the above matrix and then we'll transform it into a numpy array.

In [4]:
## np.array wrapping around the list of numbers turns the list into a numpy array 

## the reshape(5,2) method turns the array into a 2x5 matrix

myMatrix = np.array([1,2,3,4,5,3,4,5,6,7]).reshape(2,5)
print(myMatrix)

[[1 2 3 4 5]
 [3 4 5 6 7]]


What if we needed to get a single number from the matrix? We can index the matrix pretty easily.

We write it like this:

$$ M[row][column] $$ 

In computers, we always count from 0 instead of 1.

In [5]:
# get the number 2
print(myMatrix[0][1])

# get the number 7
print(myMatrix[1][4])



2
7


In [9]:
# get the first row 

print(myMatrix[0])

# get the first column

print(myMatrix[:,0])

[1 2 3 4 5]
[1 3]


Scalar Operations with Matrices :

$$ 
n * M = 
\left[ {\begin{array}{ccccc}
    n & 2n & 3n & 4n & 5n\\
   3n & 4n & 5n & 6n & 7n\\
  \end{array} } \right]
$$ 


In [10]:
def scalarOp(n: int,M: np.array):
    return n*M

print(scalarOp(3,myMatrix))

[[ 3  6  9 12 15]
 [ 9 12 15 18 21]]


Matrix Transposition:

$$
M=
\left[ {\begin{array}{ccccc}
    1 & 2 & 3 & 4 & 5\\
   3 & 4 & 5 & 6 & 7\\
  \end{array} } \right]
$$

$$
  \rightarrow 
$$
$$
  M.T=
\left[ {\begin{array}{cc}
    1 & 3 \\
    2 & 4 \\
    3 & 5 \\
    4 & 6 \\
    5 & 7 \\ 
  \end{array} } \right]
  $$


In [12]:
def transpose(M: np.array):
    return M.T

print(transpose(myMatrix))

[[1 3]
 [2 4]
 [3 5]
 [4 6]
 [5 7]]


Dot Product:

$$ M \bullet M.T $$
$$ \rightarrow $$ 

$$ 
\left[ {\begin{array}{ccccc}
    1 & 2 & 3 & 4 & 5\\
   3 & 4 & 5 & 6 & 7\\
  \end{array} } \right]
$$ 
$$ 
\bullet
$$
$$ 
\left[ {\begin{array}{cc}
    1 & 3 \\
    2 & 4 \\
    3 & 5 \\
    4 & 6 \\
    5 & 7 \\ 
  \end{array} } \right]
  $$ 
  $$ 
  \rightarrow
  $$
  $$ 
\left[ {\begin{array}{cc}
    (1*1)+(2*2)+(3*3)+(4*4)+(5*5) & (1*3)+(2*4)+(3*5)+(4*6)+(5*7) \\
    (1*3)+(2*4)+(3*5)+(4*6)+(5*7) & (3*3)+(4*4)+(5*5)+(6*6)+(7*7) \\
  \end{array} } \right]
  $$
  $$
  \rightarrow
  $$
  $$
  M \bullet M.T = 
  \left[ {\begin{array}{cc}
    55 & 85 \\
    85 & 135 \\
  \end{array} } \right]
  $$

In [13]:
print(np.dot(myMatrix, myMatrix.T))

[[ 55  85]
 [ 85 135]]
